service: dictionary-api
frameworkVersion: '3'

plugins:
  - serverless-domain-manager

provider:
  name: aws
  stage: dev # default stage
  region: us-east-1
  runtime: nodejs18.x
  deploymentMethod: direct
  httpApi:
    cors: true
  logRetentionInDays: 7
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 2
  versionFunctions: false

params:
  prod:
    domain: 'dictionary-api.vighnesh153.dev'
  dev:
    domain: 'dev-dictionary-api.vighnesh153.dev'

custom:
  customDomain:
    domainName: ${param:domain}
    basePath: ''
    certificateName: '*.vighnesh153.dev'
    apiType: http
    endpointType: regional
    autoDomain: true
    createRoute53Record: true

package:
  individually: true

layers:
  NodeModules:
    package:
      artifact: layer/nodejs.zip
    name: dictionary-api-deps-${sls:stage}

functions:
  api:
    name: dictionary-api-${sls:stage}
    handler: dist/index.handler
    events:
      - httpApi: '*'
    layers:
      - !Ref NodeModulesLambdaLayer
    package:
      patterns:
        - '!./**'
        - dist/**
