/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package interpreters.javalang.common

import kotlin.test.Test
import kotlin.test.assertContains

class LibraryTest {
    @Test
    fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertContains(classUnderTest.pikachuRandomNumber(), "pikachu-")
    }
}
