import Head from 'next/head';
import { useGithubGist } from '../hooks';

export default function Home() {
  useGithubGist();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main />
    </>
  );
}
