import Head from 'next/head';
import { useEffect, useRef } from 'react';
import { GithubGist } from '@vighnesh153/github-gist';

const personalAccessToken = '111';
const gistId = '111g';

function useEffectOnce(callback: () => void) {
  const ref = useRef(false);
  useEffect(() => {
    if (ref.current) return;
    ref.current = true;
    callback();
  }, [callback]);
}

export default function Home() {
  useEffectOnce(() => {
    (async () => {
      const gist = await GithubGist.initializeUsingGistId({ personalAccessToken, gistId });

      const fileJson = gist.createNewFile('vighnesh153.json');
      fileJson.content = JSON.stringify({ message: 'Vighnesh is the best' }, null, 2);

      const filePython = gist.createNewFile('vighnesh153.py');
      filePython.content = `print("Vighnesh is the best")`;

      const fileJs = gist.createNewFile('vighnesh153.js');
      fileJs.content = `console.log("Vighnesh is the best")`;

      await gist.save();

      const fileMd = gist.createNewFile('vighnesh153.md');
      fileMd.content = '# Vighnesh is the best';

      fileJs.content = [fileJs.content, 'console.log("Vighnesh is the best and I know it")'].join('\n');

      await gist.save();
    })();
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main />
    </>
  );
}
