import Head from 'next/head';
import { useEffect } from 'react';

const token = '111';
// eslint-disable-next-line no-console
console.log(token);

export default function Home() {
  useEffect(() => {
    // verifyGithubPAT(token);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main />
    </>
  );
}
