services:
  mongodb-dev:
    command: mongod --replSet rs0
    container_name: mongodb-dev
    image: mongo:6.0.4
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: "always"
    volumes:
      - ./mongodb-local:/data/db

  # finally, we can define the initialization server
  # this runs the `rs.initiate` command to intialize
  # the replica set and connect the three servers to each other
  #
  mongodb-dev-init:
    command: >
      mongosh --host mongodb-dev:27017 --eval 
      '
      rs.initiate({"_id": "rs0", "members": [{"_id": 0, "host" : "mongodb-dev:27017"}]});
      '
    container_name: mongodb-dev-init
    depends_on:
      - mongodb-dev
    image: mongo:6.0.4
    # This container should exit after executing the command.
    # We are using this container to just run the above command
    # which will initialize the replica set with the above instance
    restart: "no"

  local-mongo-express:
    container_name: local-mongo-express
    depends_on:
      - mongodb-dev
    environment:
      # should match the container instance name
      ME_CONFIG_MONGODB_SERVER: mongodb-dev
    image: mongo-express
    ports:
      - 8081:8081
    restart: "always"
