/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package interpreters.javalang.common

import kotlin.random.Random

class Library {
    fun pikachuRandomNumber(): String {
        return "pikachu-${Random.nextInt(1, 101)}"
    }
}
