export const styles = {
  font: {
    family: {
      sans: "var(--font-sans)",
      serif: "var(--font-serif)",
      mono: "var(--font-mono)",
    },
    size: {
      xs: "var(--text-size-xs)",
      sm: "var(--text-size-sm)",
      base: "var(--text-size-base)",
      lg: "var(--text-size-lg)",
      xl: "var(--text-size-xl)",
      "2xl": "var(--text-size-2xl)",
      "3xl": "var(--text-size-3xl)",
      "4xl": "var(--text-size-4xl)",
      "5xl": "var(--text-size-5xl)",
      "6xl": "var(--text-size-6xl)",
      "7xl": "var(--text-size-7xl)",
      "8xl": "var(--text-size-8xl)",
      "9xl": "var(--text-size-9xl)",
    },
    lineHeight: {
      xs: "var(--text-size-xs--line-height)",
      sm: "var(--text-size-sm--line-height)",
      base: "var(--text-size-base--line-height)",
      lg: "var(--text-size-lg--line-height)",
      xl: "var(--text-size-xl--line-height)",
      "2xl": "var(--text-size-2xl--line-height)",
      "3xl": "var(--text-size-3xl--line-height)",
      "4xl": "var(--text-size-4xl--line-height)",
      "5xl": "var(--text-size-5xl--line-height)",
      "6xl": "var(--text-size-6xl--line-height)",
      "7xl": "var(--text-size-7xl--line-height)",
      "8xl": "var(--text-size-8xl--line-height)",
      "9xl": "var(--text-size-9xl--line-height)",
    },
    weight: {
      thin: "var(--font-weight-thin)",
      extralight: "var(--font-weight-extralight)",
      light: "var(--font-weight-light)",
      normal: "var(--font-weight-normal)",
      medium: "var(--font-weight-medium)",
      semibold: "var(--font-weight-semibold)",
      bold: "var(--font-weight-bold)",
      extrabold: "var(--font-weight-extrabold)",
      black: "var(--font-weight-black)",
    },
  },
  color: {
    primary: "var(--color-primary)",
    secondary: "var(--color-secondary)",
    accent: "var(--color-accent)",
    text: {
      bright: "var(--color-bright)",
      default: "var(--color)",
      light: "var(--color-light)",
      dull: "var(--color-dull)",
    },
    black: "var(--color-black)",
    white: "var(--color-white)",
  },
  bg: {
    default: "var(--bg)",
    dark: "var(--bg-dark)",
    light: "var(--bg-light)",
    blend: "var(--bg-blend)",
  },
  spacing: (n: number = 1) => `calc(var(--spacing) * ${n})`,
  width: {
    prose: `var(--width-prose)`,
  },
  breakpoints: {
    sm: "var(--breakpoint-sm)",
    md: "var(--breakpoint-md)",
    lg: "var(--breakpoint-lg)",
    xl: "var(--breakpoint-xl)",
    "2xl": "var(--breakpoint-2xl)",
  },
  container: {
    "3xs": "var(--container-3xs)",
    "2xs": "var(--container-2xs)",
    xs: "var(--container-xs)",
    sm: "var(--container-sm)",
    md: "var(--container-md)",
    lg: "var(--container-lg)",
    xl: "var(--container-xl)",
    "2xl": "var(--container-2xl)",
    "3xl": "var(--container-3xl)",
    "4xl": "var(--container-4xl)",
    "5xl": "var(--container-5xl)",
    "6xl": "var(--container-6xl)",
    "7xl": "var(--container-7xl)",
  },
  border: {
    radius: {
      xs: "var(--radius-xs)",
      sm: "var(--radius-sm)",
      md: "var(--radius-md)",
      lg: "var(--radius-lg)",
      xl: "var(--radius-xl)",
      "2xl": "var(--radius-2xl)",
      "3xl": "var(--radius-3xl)",
      "4xl": "var(--radius-4xl)",
      full: "var(--radius-full)",
    },
  },
  shadow: {
    regular: {
      "2xs": (color: string = "rgb(0 0 0 / 0.05)") => `0 1px ${color}`,
      xs: (color: string = "rgb(0 0 0 / 0.05)") => `0 1px 2px 0 ${color}`,
      sm: (color: string = "rgb(0 0 0 / 0.1)") =>
        `0 1px 3px 0 ${color}, 0 1px 2px -1px ${color}`,
      md: (color: string = "rgb(0 0 0 / 0.1)") =>
        `0 4px 6px -1px ${color}, 0 2px 4px -2px ${color}`,
      lg: (color: string = "rgb(0 0 0 / 0.1)") =>
        `0 10px 15px -3px ${color}, 0 4px 6px -4px ${color}`,
      xl: (color: string = "rgb(0 0 0 / 0.1)") =>
        `0 20px 25px -5px ${color}, 0 8px 10px -6px ${color}`,
      "2xl": (color: string = "rgb(0 0 0 / 0.25)") =>
        `0 25px 50px -12px ${color}`,
    },
    inset: {
      "2xs": (color: string = "rgb(0 0 0 / 0.05)") => `inset 0 1px ${color}`,
      xs: (color: string = "rgb(0 0 0 / 0.05)") => `inset 0 1px 1px ${color}`,
      sm: (color: string = "rgb(0 0 0 / 0.05)") => `inset 0 2px 4px ${color}`,
    },
    drop: {
      xs: (color: string = "rgb(0 0 0 / 0.05)") => `0 1px 1px ${color}`,
      sm: (color: string = "rgb(0 0 0 / 0.15)") => `0 1px 2px ${color}`,
      md: (color: string = "rgb(0 0 0 / 0.12)") => `0 3px 3px ${color}`,
      lg: (color: string = "rgb(0 0 0 / 0.15)") => `0 4px 4px ${color}`,
      xl: (color: string = "rgb(0 0 0 / 0.1)") => `0 9px 7px ${color}`,
      "2xl": (color: string = "rgb(0 0 0 / 0.15)") => `0 25px 25px ${color}`,
    },
    text: {
      "2xs": (color: string = "rgb(0 0 0 / 0.15)") => `0px 1px 0px ${color}`,
      xs: (color: string = "rgb(0 0 0 / 0.2)") => `0px 1px 1px ${color}`,
      sm: (color: string = "rgb(0 0 0 / 0.075)") =>
        `0px 1px 0px ${color}, 0px 1px 1px ${color}, 0px 2px 2px ${color}`,
      md: (color: string = "rgb(0 0 0 / 0.1)") =>
        `0px 1px 1px ${color}, 0px 1px 2px ${color}, 0px 2px 4px ${color}`,
      lg: (color: string = "rgb(0 0 0 / 0.1)") =>
        `0px 1px 2px ${color}, 0px 3px 2px ${color}, 0px 4px 8px ${color}`,
    },
  },
  blur: {
    xs: "var(--blur-xs)",
    sm: "var(--blur-sm)",
    md: "var(--blur-md)",
    lg: "var(--blur-lg)",
    xl: "var(--blur-xl)",
    "2xl": "var(--blur-2xl)",
    "3xl": "var(--blur-3xl)",
  },
  perspective: {
    dramatic: "var(--perspective-dramatic)",
    near: "var(--perspective-near)",
    normal: "var(--perspective-normal)",
    midrange: "var(--perspective-midrange)",
    distant: "var(--perspective-distant)",
  },
  aspect: {
    video: "var(--aspect-video)",
    square: "var(--aspect-square)",
  },
  transition: {
    curve: {
      easeIn: "var(--ease-in)",
      easeOut: "var(--ease-out)",
      easeInOut: "var(--ease-in-out)",
    },
  },
  animation: {
    spin: "var(--animate-spin)",
    ping: "var(--animate-ping)",
    pulse: "var(--animate-pulse)",
    bounce: "var(--animate-bounce)",
  },
  zIndex: {
    px: "var(--z-px)",
    mobileStepper: "var(--z-mobile-stepper)",
    fab: "var(--z-fab)",
    appBar: "var(--z-app-bar)",
    drawer: "var(--z-drawer)",
    modal: "var(--z-modal)",
    snackbar: "var(--z-snackbar)",
    tooltip: "var(--z-tooltip)",
  },
};
