#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./node_modules/.bin/lint-staged --debug

# pre-commits for nodejs-tools
if git diff --cached --name-only | grep --quiet "nodejs-tools/"
then
  cd nodejs-tools && npm install && cd ..
  cd nodejs-tools && npm run lint && cd ..
  cd nodejs-tools && npm run test && cd ..
fi
