service: '#####################'
frameworkVersion: '3'

plugins:
  - serverless-domain-manager

provider:
  name: aws
  stage: dev  # default stage
  region: us-east-1
  runtime: nodejs18.x
  deploymentMethod: direct
  httpApi:
    cors: true
  logRetentionInDays: 7
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 2
  versionFunctions: false

params:
  prod:
    domain: '#####################.aws.vighnesh153.com'
  dev:
    domain: 'dev-#####################.aws.vighnesh153.com'

custom:
  customDomain:
    domainName: ${param:domain}
    basePath: ''
    certificateName: '*.vighnesh153.com'
    apiType: http
    endpointType: regional
    autoDomain: true
    createRoute53Record: true

package:
  patterns:
    - '!./**'
    - dist/**

layers:
  NodeModules:
    package:
      patterns:
        - 'layer/**'
      artifact: layer/nodejs.zip
    name: ${sls:stage}-#######################-deps

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi: '*'
    layers:
      - !Ref NodeModulesLambdaLayer
