name: Cloudflare workers

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read   # This is required for actions/checkout
  security-events: write
  actions: read

jobs:
  cloudflare-workers-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Deploy Cloudflare workers
        run: npm run cloudflare:workers:deploy:prod
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_AUTH_EMAIL: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}
