name: Commitlint Commit Message

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-commitlint-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Validate all commits from PR
        run: |
          npx commitlint \
            --from ${{ github.event.pull_request.base.sha }} \ 
            --to ${{ github.event.pull_request.head.sha }} \ 
            --verbose
