name: Commitlint Commit Message

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-commitlint-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - uses: wagoid/commitlint-github-action@v5

#      - name: Validate all commits from PR
#        run: |
#          BASE_SHA="${{ github.event.pull_request.base.sha }}"
#          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
#          npx commitlint --from "$BASE_SHA" --to "$HEAD_SHA" --verbose
