name: deno-ci

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "deno-tools/**"
  pull_request:
    paths:
      - "deno-tools/**"

jobs:
  deno-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./deno-tools

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      # Check if all deno projects are ok
      - run: export PIKA_PATH="$(pwd)"; for dir in */; do
          cd $PIKA_PATH/$dir;
          deno lint && deno fmt --check && deno test --permit-no-files
          done
