name: deno-ci
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "tools-deno/**"
  pull_request:
    paths:
      - "tools-deno/**"

jobs:
  deno-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./tools-deno

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      # Check if all deno projects are ok
      - run: |
          export PIKA_PATH="$(pwd)"; 
          for dir in */; do
            cd $PIKA_PATH/$dir;
            echo "Checking - $(pwd)\n";
            deno lint && deno fmt --check && deno test -A --permit-no-files;
          done
