name: Instagram AI Image Publish

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: |
            npm -w @vighnesh153/ui-automation run build
            npm -w @vighnesh153/ui-automation run openai:random-image
          browser: chrome
          project: ./packages/instagram-api
          config-file: ./packages/instagram-api/cypress.config.ts
          spec: cypress/e2e/instagram-ai-image.cy.ts
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INSTAGRAM_CREDENTIALS: ${{ secrets.INSTAGRAM_CREDENTIALS_AI_IMAGE_BOT }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
