name: Instagram AI Image Publish

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm -w @vighnesh153/ui-automation run build

      - name: Download image
        run: npm -w @vighnesh153/ui-automation run openai:random-image
        env:
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}

      - name: List down the directory
        run: ls -la && ls -la ./packages/ui-automation && pwd

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: false
          browser: chrome
          working-directory: packages/instagram-api
          spec: cypress/e2e/instagram-ai-image.cy.ts
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INSTAGRAM_CREDENTIALS: ${{ secrets.INSTAGRAM_CREDENTIALS_AI_IMAGE_BOT }}
