name: jvm-ci

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "jvm-tools/**"
  pull_request:
    paths:
      - "jvm-tools/**"

jobs:
  jvm-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./jvm-tools

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "adopt-openj9"
          java-version: "21"

      - run: export PIKA_PATH="$(pwd)"; for dir in */; do
          cd $PIKA_PATH/$dir;
          ./gradlew test;
          done
