name: nodejs-deploy-aws-serverless-tools

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  security-events: write
  actions: read

jobs:
  nodejs-deploy-aws-serverless-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: MySessionName
          aws-region: us-east-1

      - name: install dependencies in root
        run: npm ci

      - name: install dependencies in nodejs-tools
        run: npm ci
        working-directory: ./nodejs-tools

      - name: Deploy AWS tools
        run: npm run deploy:prod -- --filter=./nodejs-aws-serverless-tools/*
        working-directory: ./nodejs-tools
