name: nodejs-eslint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  nodejs-eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install && cd nodejs-tools && npm install && cd ..

      - name: Run ESLint
        run: cd nodejs-tools && npm run lint
