name: nodejs-eslint

on:
  push:
    branches: ["main"]
    paths:
      - /nodejs-tools/*
  pull_request:
    branches: ["main"]
    paths:
      - /nodejs-tools/*

jobs:
  nodejs-eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nodejs-tools
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # install deps
      - run: npm install

      - name: Run ESLint
        run: npm run lint
