name: nodejs-deploy-cloudflare-tools

on:
  workflow_dispatch:

permissions:
  contents: read # This is required for actions/checkout
  security-events: write
  actions: read

jobs:
  nodejs-deploy-cloudflare-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: install dependencies in root
        run: npm ci

      - name: install dependencies in nodejs-tools
        run: npm ci
        working-directory: ./nodejs-tools

      - name: Deploy Cloudflare tools
        run: npm run deploy:prod -- --filter=./nodejs-cloudflare-tools/*
        working-directory: ./nodejs-tools
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_AUTH_EMAIL: ${{ secrets.CLOUDFLARE_AUTH_EMAIL }}
