# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: nodejs-ci

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "nodejs-tools/**"
  pull_request:
    paths:
      - "nodejs-tools/**"

jobs:
  nodejs-ci:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: ./nodejs-tools

    steps:
      - uses: actions/checkout@v3

      # install deps
      - run: npm install

      # Run lint tools
      - run: npm run lint

      # Build the project
      - run: npm run build

      # Test the project
      - run: npm run test
