name: nodejs-publish

on:
  workflow_dispatch:
    inputs:
      shouldUpdateVersion:
        required: true
        type: choice
        description: Update the version?
        default: 'false'
        options:
          - true
          - false
      shouldGitTag:
        required: true
        type: choice
        description: Create a tag commit?
        default: 'false'
        options:
          - true
          - false
      shouldPublishToNPM:
        required: true
        type: choice
        description: Publish to NPM
        default: 'false'
        options:
          - true
          - false
      newVersion:
        required: true
        description: Specify the new version (if not updating, specify the current one)
      publishArgs:
        required: false
        description: customize the arguments passed to 'npm publish'
        default: '--workspace nodejs-packages --tag latest'

jobs:
  nodejs-publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies in root
        run: npm ci

      - name: install dependencies in nodejs-tools
        run: npm ci
        working-directory: ./nodejs-tools

      - name: build packages
        run: npm run build -- --filter=./nodejs-packages/*
        working-directory: ./nodejs-tools

      - name: Config git metadata
        run: |
          git config --global user.name 'Vighnesh Raut'
          git config --global user.email 'me@vighnesh153.com'

      - name: Update the version in the packages
        if: ${{ inputs.shouldUpdateVersion == 'true' }}
        run: |
          npm version ${{ inputs.newVersion }} --git-tag-version=false --allow-same-version=true --workspace=./nodejs-packages
          git add .
          git commit -m "build: update the npm version to ${{ inputs.newVersion }}" --no-verify
          git push
        working-directory: ./nodejs-tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the packages
        if: ${{ inputs.shouldPublishToNPM == 'true' }}
        run: |
          npm run changeStarToSpecificVersion
          GIT_PAGER=cat git diff

          npm publish ${{ inputs.publishArgs }}
        working-directory: ./nodejs-tools
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a git tag and push
        if: ${{ inputs.shouldGitTag == 'true' }}
        run: |
          git tag v${{ inputs.newVersion }}
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
