name: Publish all packages to NPM

on:
  workflow_dispatch:
    inputs:
      shouldUpdateVersion:
        required: true
        type: choice
        description: Update the version?
        default: "false"
        options:
          - true
          - false
      shouldGitTag:
        required: true
        type: choice
        description: Create a tag commit?
        default: "false"
        options:
          - true
          - false
      shouldPublishToNPM:
        required: true
        type: choice
        description: Publish to NPM
        default: "false"
        options:
          - true
          - false
      newVersion:
        required: true
        description: Specify the new version (if not updating, specify the current one)
      publishTag:
        required: false
        description: The tag which should be used to publish
        default: '--tag latest'
      publishArgs:
        required: false
        description: customize the arguments passed to 'npm publish'
        default: '--workspace packages'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:packages

      - name: Config git metadata
        run: |
          git config --global user.name 'Vighnesh Raut'
          git config --global user.email 'me@vighnesh153.com'

      - name: Update the version in the packages
        if: ${{ inputs.shouldUpdateVersion == 'true' }}
        run: |
          npm version ${{ inputs.newVersion }} --git-tag-version=false --allow-same-version=true --workspace=./packages
          git add .
          git commit -m "build: update the npm version to ${{ inputs.newVersion }}" --no-verify
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the packages
        if: ${{ inputs.shouldPublishToNPM == 'true' }}
        run: |
          npm run changeStarToSpecificVersion
          GIT_PAGER=cat git diff

          npm publish ${{ inputs.publishTag }} ${{ inputs.publishArgs }}
          npm logout
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a git tag and push
        if: ${{ inputs.shouldGitTag == 'true' }}
        run: |
          git tag v${{ inputs.newVersion }}
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
